### PR TITLE
Add pytest to Github actions

### PR DESCRIPTION
**Pull request by NielsRogge**
This PR adds pytest to the Github actions, to make sure tests are run each time a PR is made.

### CODE REVIEW

**Comment by RobbeSneyders** [comment]
Since Poetry is not running in a virtual environment, it create and manages its own. This is cleaner for CI/CD, as Poetry's owns dependencies are not installed in the virtual environment. You can run a command in the virtual environment by running `poetry run <command>`.

See the [docs](https://python-poetry.org/docs/basic-usage/#using-your-virtual-environment) for more info.

**Comment by NielsRogge** [comment]
@RobbeSneyders thanks, have added back the "io" module to make all tests pass

**Comment by PhilippeMoussalli** [comment]
> @RobbeSneyders thanks, have added back the "io" module to make all tests pass

Can you remove `io` and `test_io` altogether, those are not needed

**Review by PhilippeMoussalli — APPROVED** [review]
Thanks for adding this. Just remove all the `io` stuff and it's ready to merge

**Comment by NielsRogge** [comment]
@PhilippeMoussalli that means I can also remove the [copy_folder](https://github.com/ml6team/express/blob/14ab275e004b81ab95c70bea8720f23337cb0e4f/express/gcp_storage.py#L74) and [copy_file](https://github.com/ml6team/express/blob/14ab275e004b81ab95c70bea8720f23337cb0e4f/express/gcp_storage.py#L144) methods which rely on it?

**Comment by PhilippeMoussalli** [comment]
> [@PhilippeMoussalli](/PhilippeMoussalli)

yes they can be removed

**Comment by PhilippeMoussalli** [comment]
> @PhilippeMoussalli that means I can also remove the [copy_folder](https://github.com/ml6team/express/blob/14ab275e004b81ab95c70bea8720f23337cb0e4f/express/gcp_storage.py#L74) and [copy_file](https://github.com/ml6team/express/blob/14ab275e004b81ab95c70bea8720f23337cb0e4f/express/gcp_storage.py#L144) methods which rely on it?

yes they can be removed

**Comment by NielsRogge** [comment]
I'll merge this and remove the io files in a separate PR, as they are still used in the soon-to-be-legacy storage helpers

**Pull request merged**
